version: 2
updates:
  - package-ecosystem: npm
    directory: /
    target-branch: develop
    schedule:
      interval: weekly
    groups:
      cloudflare:
        patterns: ["wrangler", "miniflare"]
        update-types: ["minor", "patch"]
      npm:
        patterns: ["*"]
        exclude-patterns: ["wrangler", "miniflare"]
        update-types: ["minor", "patch"]
  - package-ecosystem: github-actions
    directory: /
    target-branch: develop
    schedule:
      interval: weekly
    groups:
      actions:
        patterns: ["*"]
        update-types: ["minor", "patch"]
