import { expect, test } from "@playwright/test";

const answer = {
  hypothesis: "Database waits may explain the slow tail.",
  checks: [
    "Inspect trace samples for database waits.",
    "Inspect the connection pool measurements.",
  ],
  unknown: "The cause of the increased wait is unknown.",
};
test("AI separates scenario facts, reviewed interpretation and model suggestions", async ({
  page,
}) => {
  await page.route("**/api/triage?*", (route) =>
    route.fulfill({ json: { scenario: "latency", answer } }),
  );
  await page.goto("/experiments/#triage");
  const card = page.locator("#triage");
  await expect.soft(card).toContainText("Choose a fictional incident");
  await expect
    .soft(card)
    .toContainText(
      "Prepared for this scenario, not generated by your request.",
    );
  await expect(
    card.getByRole("heading", { name: "Scenario facts" }),
  ).toBeVisible();
  await expect(
    card.getByText("Reviewed interpretation", { exact: true }),
  ).toBeVisible();
  await card.getByRole("button", { name: "Run triage", exact: true }).click();
  await expect(
    card.getByRole("heading", { name: "Model suggestion", exact: true }),
  ).toBeVisible();
  await expect(card.locator("[data-triage-answer] li")).toHaveCount(2);
  await expect(
    card.getByRole("heading", {
      name: "Suggested read-only checks",
      exact: true,
    }),
  ).toBeVisible();
  await expect(card.locator("[data-triage-status]")).not.toContainText(
    "evidence above",
  );
  await page.locator("#triage-scenario").selectOption("replicas");
  await expect(card.locator("[data-triage-evidence]")).toContainText(
    "HPA recommends",
  );
  await expect(card.locator("[data-triage-interpretation]")).toContainText(
    "scheduler",
  );
  await expect(card.locator("[data-triage-answer]")).toBeHidden();
});

test("public AI waits for human verification and sends only its token and scenario", async ({
  page,
}) => {
  let inference = 0;
  let releaseConfiguration!: () => void;
  const pendingConfiguration = new Promise<void>((resolve) => {
    releaseConfiguration = resolve;
  });
  let releaseAnswer!: () => void;
  const pendingAnswer = new Promise<void>((resolve) => {
    releaseAnswer = resolve;
  });
  await page.route("**/api/triage-config", async (route) => {
    await pendingConfiguration;
    return route.fulfill({ json: { local: false, siteKey: "public-fixture" } });
  });
  await page.route(
    "https://challenges.cloudflare.com/turnstile/v0/api.js?render=explicit",
    (route) =>
      route.fulfill({
        contentType: "application/javascript",
        body: `window.turnstile={render(element,options){window.fixtureVerify=options.callback;return 'widget';},execute(){},remove(){}};`,
      }),
  );
  await page.route("**/api/triage?*", async (route) => {
    inference++;
    expect(route.request().headers()["cf-turnstile-response"]).toBe(
      "fixture-human-token",
    );
    expect(route.request().postData()).toBe(null);
    await pendingAnswer;
    return route.fulfill({ json: { scenario: "latency", answer } });
  });
  await page.goto("/experiments/#triage");
  await expect
    .soft(page.locator("#triage"))
    .toHaveAttribute("data-triage-phase", "ready");
  await page.getByRole("button", { name: "Run triage", exact: true }).click();
  await expect
    .soft(page.locator("#triage"))
    .toHaveAttribute("data-triage-phase", "preparing");
  releaseConfiguration();
  await expect
    .poll(() =>
      page.evaluate(
        () =>
          typeof (window as unknown as { fixtureVerify?: unknown })
            .fixtureVerify,
      ),
    )
    .toBe("function");
  expect(inference).toBe(0);
  await expect
    .soft(page.locator("#triage"))
    .toHaveAttribute("data-triage-phase", "verifying");
  await page.evaluate(() =>
    (
      window as unknown as { fixtureVerify: (token: string) => void }
    ).fixtureVerify("fixture-human-token"),
  );
  await expect
    .soft(page.locator("#triage"))
    .toHaveAttribute("data-triage-phase", "waiting");
  releaseAnswer();
  await expect(page.locator("[data-triage-answer]")).toContainText(
    answer.hypothesis,
  );
  expect(inference).toBe(1);
  await expect(page.locator("#triage")).toHaveAttribute(
    "data-triage-phase",
    "answered",
  );
  const answerBounds = (await page
    .locator("[data-triage-answer]")
    .boundingBox())!;
  const referenceBounds = (await page
    .locator(".triage-reference")
    .boundingBox())!;
  expect(referenceBounds.y).toBeGreaterThanOrEqual(
    answerBounds.y + answerBounds.height,
  );
  await page.locator("#triage-scenario").selectOption("replicas");
  await expect(page.locator("#triage")).toHaveAttribute(
    "data-triage-phase",
    "ready",
  );
});

test("local AI availability checks do not claim verification or inference", async ({
  page,
}) => {
  let complete!: () => void;
  const pending = new Promise<void>((resolve) => {
    complete = resolve;
  });
  let requests = 0;
  await page.route("**/api/triage-config", (route) =>
    route.fulfill({ json: { local: true } }),
  );
  await page.route("**/api/triage?*", async (route) => {
    requests++;
    await pending;
    return route.fulfill({
      status: 503,
      json: { error: "local_inference_unavailable" },
    });
  });
  await page.goto("/experiments/#triage");
  await page.getByRole("button", { name: "Run triage", exact: true }).click();
  await expect.poll(() => requests).toBe(1);
  await expect
    .soft(page.locator("#triage"))
    .toHaveAttribute("data-triage-phase", "preparing");
  await expect
    .soft(page.locator("[data-triage-status]"))
    .not.toContainText(/Verifying|Waiting for the model/);
  complete();
  await expect(page.locator("[data-triage-status]")).toContainText(
    "Local preview does not run inference",
  );
  await expect(page.locator("#triage")).toHaveAttribute(
    "data-triage-phase",
    "unavailable",
  );
});

test("verification fits a narrow viewport and a scenario change cancels its pending answer", async ({
  page,
}) => {
  await page.setViewportSize({ width: 320, height: 874 });
  let requests = 0;
  await page.route("**/api/triage-config", (route) =>
    route.fulfill({ json: { local: false, siteKey: "public-fixture" } }),
  );
  await page.route(
    "https://challenges.cloudflare.com/turnstile/v0/api.js?render=explicit",
    (route) =>
      route.fulfill({
        contentType: "application/javascript",
        body: `window.turnstile={render(element,options){const widget=document.createElement('div');widget.textContent='Verification fixture';widget.style.width=options.size==='compact'?'150px':'300px';element.append(widget);window.fixtureVerify=options.callback;return 'widget';},execute(){},remove(){}};`,
      }),
  );
  await page.route("**/api/triage?*", (route) => {
    requests++;
    return route.fulfill({ json: { scenario: "latency", answer } });
  });
  await page.goto("/experiments/#triage");
  await page.getByRole("button", { name: "Run triage", exact: true }).click();
  await expect(page.getByText("Verification fixture")).toBeVisible();
  const widgetBounds = await page
    .getByText("Verification fixture")
    .boundingBox();
  const sourceBounds = await page.locator(".triage-source").boundingBox();
  expect(widgetBounds!.width).toBeLessThanOrEqual(sourceBounds!.width);
  expect(
    await page.evaluate(() => document.documentElement.scrollWidth),
  ).toBeLessThanOrEqual(320);
  await page.locator("#triage-scenario").selectOption("replicas");
  await expect(page.getByText("Verification fixture")).toHaveCount(0);
  await expect(
    page.getByRole("button", { name: "Run triage", exact: true }),
  ).toBeEnabled();
  expect(requests).toBe(0);
});

test("a suspended AI request explains how to retry the always-open lab", async ({
  page,
}) => {
  let requests = 0;
  await page.route("**/api/triage?*", () => {
    requests++;
  });
  await page.goto("/experiments/#triage");
  const run = page.getByRole("button", { name: "Run triage", exact: true });
  await run.click();
  await expect.poll(() => requests).toBe(1);
  await page.evaluate(() => window.dispatchEvent(new Event("pagehide")));
  await expect(run).toBeEnabled();
  await expect(page.locator("[data-triage-status]")).toHaveText(
    "Request stopped. Press Run triage to try again.",
  );
  await expect(page.locator("#triage")).toHaveAttribute(
    "data-triage-phase",
    "unavailable",
  );
  await expect(page.locator("[data-triage-answer]")).toBeHidden();
  await expect(page.locator("[data-triage-interpretation]")).toBeVisible();
  await run.click();
  await expect.poll(() => requests).toBe(2);
  await page.locator("#triage-scenario").selectOption("telemetry");
  await expect(run).toBeEnabled();
});

test("AI occupies full width below the compact Cloudflare collection", async ({
  page,
}) => {
  await page.setViewportSize({ width: 1280, height: 900 });
  await page.goto("/experiments/#triage");
  const bounds = await page.locator("#triage").boundingBox();
  const collection = await page.locator(".live-grid").boundingBox();
  expect(bounds!.width).toBeGreaterThan(collection!.width * 0.95);
  expect(bounds!.y).toBeGreaterThanOrEqual(collection!.y + collection!.height);
  await page.setViewportSize({ width: 402, height: 874 });
  expect(
    await page.evaluate(() => document.documentElement.scrollWidth),
  ).toBeLessThanOrEqual(402);
});

test("changing scenario releases Run while verification code is still downloading", async ({
  page,
}) => {
  let scriptRequests = 0;
  let inference = 0;
  await page.route("**/api/triage-config", (route) =>
    route.fulfill({ json: { local: false, siteKey: "public-fixture" } }),
  );
  await page.route(
    "https://challenges.cloudflare.com/turnstile/v0/api.js?render=explicit",
    () => {
      scriptRequests++;
    },
  );
  await page.route("**/api/triage?*", (route) => {
    inference++;
    return route.fulfill({ json: { scenario: "latency", answer } });
  });
  await page.goto("/experiments/#triage");
  const run = page.getByRole("button", { name: "Run triage", exact: true });
  await run.click();
  await expect.poll(() => scriptRequests).toBe(1);
  await page.locator("#triage-scenario").selectOption("replicas");
  await expect(run).toBeEnabled({ timeout: 1000 });
  await expect(page.locator("[data-triage-status]")).toHaveText(
    "Ready. No model request until you press Run triage.",
  );
  expect(inference).toBe(0);
  // The new caller can wait for the same script; cancellation must not restart it.
  await run.click();
  await expect(run).toBeDisabled();
  await page.locator("#triage-scenario").selectOption("telemetry");
  await expect(run).toBeEnabled({ timeout: 1000 });
  expect(scriptRequests).toBe(1);
});

for (const colourScheme of ["light", "dark"] as const) {
  test(`AI opens with a useful reference and full-width artwork in ${colourScheme}`, async ({
    page,
  }, testInfo) => {
    await page.emulateMedia({ colorScheme: colourScheme });
    for (const width of [1280, 620, 402, 320]) {
      await page.setViewportSize({ width, height: 900 });
      await page.goto("/experiments/#triage");
      const card = page.locator("#triage");
      await expect(card.locator(".experiment-settings")).toHaveCount(0);
      await expect(card.locator("[data-triage-interpretation]")).toBeVisible();
      await expect(
        card.getByRole("combobox", { name: "Choose a scenario" }),
      ).toBeEnabled();
      expect(
        (await card.getByRole("combobox").boundingBox())!.height,
      ).toBeGreaterThanOrEqual(44);
      const preview = await card.locator(".experiment-visual").boundingBox();
      expect(preview!.height).toBeLessThanOrEqual(110);
      const stage = (await card.locator(".experiment-stage").boundingBox())!;
      const cardBounds = (await card.boundingBox())!;
      expect
        .soft(Math.abs(stage.width - cardBounds.width))
        .toBeLessThanOrEqual(1);
      const run = await card.locator("[data-triage-run]").boundingBox();
      const status = await card.locator("[data-triage-status]").boundingBox();
      expect(status!.y - run!.y - run!.height).toBeLessThan(25);
      expect(
        await page.evaluate(() => document.documentElement.scrollWidth),
      ).toBeLessThanOrEqual(width);
      const source = (await card.locator(".triage-source").boundingBox())!;
      const result = (await card.locator(".triage-result").boundingBox())!;
      if (width >= 768) {
        expect(Math.abs(source.y - result.y)).toBeLessThanOrEqual(1);
        expect(result.x).toBeGreaterThan(source.x + source.width);
      } else {
        expect(result.y).toBeGreaterThanOrEqual(source.y + source.height);
        expect(Math.abs(result.x - source.x)).toBeLessThanOrEqual(1);
      }
      if (width === 1280 || width === 402)
        await card.screenshot({ path: testInfo.outputPath(`ai-${width}.png`) });
    }
  });
}

test("failed AI requests settle the artwork without hiding the reference", async ({
  page,
}) => {
  await page.route("**/api/triage?*", (route) =>
    route.fulfill({
      status: 503,
      json: { error: "model_response_incomplete" },
    }),
  );
  await page.goto("/experiments/#triage");
  await page.getByRole("button", { name: "Run triage", exact: true }).click();
  await expect(page.locator("[data-triage-status]")).toContainText(
    "Nothing partial is shown",
  );
  await expect(page.locator("#triage")).toHaveAttribute(
    "data-triage-phase",
    "unavailable",
  );
  await expect(page.locator("[data-triage-answer]")).toBeHidden();
  await expect(page.locator("[data-triage-interpretation]")).toBeVisible();
  expect(
    await page
      .locator(".preview-live-triage")
      .evaluate(
        (el) =>
          el
            .getAnimations({ subtree: true })
            .filter((a) => a.playState === "running").length,
      ),
  ).toBe(0);
});
